import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() { 
const router = useRouter();
const [formData, setFormData] = useState({
  firstName:'',
  username:''
})

const CheckLogin = () => {
  console.log(formData.firstName)
  console.log(formData)

  if(formData.username !==null){
    router.push({
      pathname:'./counter',
      query: {
        username: formData.username
      }
    })
  }


}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <label className={styles.text}>First Name:</label>
        <input className={styles.input}
        type="text"
        id="first"
        name="first"
        pattern="[A-Z]{1}[a-z{2,10"
        title="The first letter should be capital"
        onChange={(e=> setFormData({...formData, firstName: e.target.value}))}
        />

        <label className={styles.text}>Userame:</label>
        <input className={styles.input}
        type="text"
        id="first"
        name="first"
        pattern="[A-Z]{1}[a-z{2,10"
        title="The first letter should be capital"
        minLength="5"
        maxLength="10"
        onChange={(e=> setFormData({...formData, username: e.target.value}))}
        />

        <button type="submit" onClick={() => CheckLogin()}>Submit</button>
      </main>
    </>
  )
}
